### ISSUE TITLE
Can't build it

### ISSUE THREAD

**Issue by mohd-akram** [codebrainz/morse#1]
First, the README doesn't mention that you need to install pkgconfig, autoconf and automake. It mentions `./configure` but that doesn't exist and I had to run `./autogen.sh`. Now I'm stuck at the `make` stage:

```
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       main.o
make[2]: *** No rule to make target `../src/libmorse.la', needed by `morse'.  Stop.
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

**Comment by codebrainz** [comment]
`./autogen.sh` generates `./configure` script for when building from a source repository. The dependencies are standard tools on Linux and I believe they also come with OSX IDE/development tools.

There's not enough info in your paste to tell what's wrong when building. I would suggest to re-run `autogen.sh` to (re)generate the `./configure` script and re-run the `./configure` script (use `./configure --help` first to see the options). Then run `make` again and paste all errors it reports if it doesn't build.

Note: this was just a little tool I whipped up 6 years ago and haven't touched since, and have never built on OSX, so I cannot be certain all of the issues. If you know C, it should be relatively straight forward to just take the C/H files and build it yourself using your favourite build system.

**Comment by mohd-akram** [comment]
So I've solved the mystery. It seems automake's behavior changed between version 1.15.1 and 1.16.1, breaking the build. The old version generated a Makefile with this:

    all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(HEADERS) config.h

The new version generates this:

    all-am: Makefile $(PROGRAMS) $(LTLIBRARIES) $(HEADERS) config.h

Basically, the new version tries to build the program, `morse`, before building `libmorse`.

For anyone who wants to build this without autoconf:

    cc -DPACKAGE=\"morse\" -DPACKAGE_VERSION=\"0.01\" -DBEEP_BACKEND_PORTAUDIO -lportaudio -o morse src/*.c

I'm getting crackling sounds though, even when nothing is being played.
